# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b9178eca45462353cba824561afb8176028140fc62f7e940d02e3ba40fd6a59ebedbc79595bc5f40e97d2e58a74c7cdf742aeb9952d85e37421ccfe1f515eb6

test:
  secret_key_base: 1c1bdb2e91abd8327880457eed55ee43792b3ead4b345fd2640e574ee03d3b01578f90e5d14cc8f189ae77c9f3cf8645b81bfc237f30ba6557ec212b703ea071

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
